class StateService {
  static final List<String> states = [
    'Perfect',
    'Perfect - Ed Sheeran',
    'Perfect - One direction',
    'Sprinter',
    'Sprinter - Dave',
    'Who Told You',
    'Miracle',
    'Miracle - Calvin Harris',
    'Giving Me',
    'Giving Me - Jazzy',
    'GoodLife',
    'GoddLife - Roro',
    'GoodTime',
    'As It Was',
    'As It Was - harry styles',
    'Summer',
    'Summer time',
    'Summer - Calvin Harris',
    'Call Me Maybe',
    'Payphone - Maroon5',
    'Light',
    'Light - Ellie Goulding',
    'Love Me Like You Do',
    'Glad You Came - The Weekend',
    'Castle on the hill',
    'Cruel summer - Taylor Swift',
    'Ed Sheerand',
    'Taylor Swift',
    'Justin Bieber',
    'Lover',
    'Love Yourselt',
    'Love on me',
    'Baby - Justin Bieber',
    'Maroon 5',
    'Train',
    'Rihanna',
    'Sơn Tùng MTP',
    'Amee',
    'Jason Mraz',
    'Bruno Mars',
    'Đan Trường',
    'Min',
    'Boyfriends',
    'All around the world',
    'Call me may be',
    'Pink',
    'Just Give me a reason - Pink',
    'Try - Pink',
    'Katy Perry',
    'Believer - Imagine Dragon',
    'Thunder - Imagin Dragon',
    'Imagine Dragon',
    'Hello - Adele',
    'Adele',
    'Home - Philip',
    'Scream',
    'Usher',
    'Erick',
    'Ne-yo',
    'So sick - Ne-yo',
    'Because of you - Ne-yo',
    'Turn up the music - Chris Brown',
    'Chris Brown',
    'Christina Perri',
    'A thousand years - Christina Perri',
    'Burn It Down - Linkin Park',
    'Adorn - Miguel',
    'Hotline Bling - Drake',
    'We Are Never Ever Getting Back Together - Taylor Swift',
    'Happy - Pharrell Williams',
    'Sorry - Justin Bieber',
    ' Can\'t Stop the Feeling! - Justin Timberlake',
    'Bad Guy"- Billie Eilish',
    'Counting Stars - OneRepublic',
    'OneRepublic',
    'Shape of You" - Ed Sheeran',
    'Thinking Out Loud - Ed Sheeran',
    'Roar - Katy Perry',
    'Shake It Off - Taylor Swift',
    'Radioactive - Imagine Dragons',
    'Big',
    'Can\'t Feel My Face - The Weeknd',
    'Just the Way You Are - Bruno Mars',
    'Poker Face - Lady Gaga',
    'Titanium - David Guetta ft. Sia',
    'The A Team - Ed Sheeran',
    'Style - Taylor Swift',
  ];

  static List<String> getSuggestions(String query) {
    List<String> matches = [];
    matches.addAll(states);
    matches.retainWhere((s) => s.toLowerCase().contains(query.toLowerCase()));
    return matches;
  }
}
